language: node_js
node_js:
  - "11.10.0"
script:
  - cd SmartphoneCompanionWeb
  - ng build --configuration=firebase
  - cd ..
install:
  - npm install -g firebase-tools
  - cd SmartphoneCompanionFirebase
  - npm install
  - cd ..
  - cd SmartphoneCompanionWeb
  - npm install
  - cd ..
after_success:
  - cd SmartphoneCompanionFirebase
  - firebase deploy --project smartphone-companion --token $FIREBASE_TOKEN