language: node_js
node_js:
  - "11.10.0"
script:
  - echo "Deploying..."
  - cd SmartphoneCompanionWeb
  - ng build --prod
install:
  - cd SmartphoneCompanionWeb
  - npm install
  - npm install -g firebase-tools
  - cd ..
after_success:
  - firebase deploy --project smartphone-companion --token $FIREBASE_TOKEN